<?php // -*- mode: php; tab-width: 2 -*-
//
//    Copyright (C) 2010 Johan Euphrosine
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

function os_poker_skin_menu() {
  return array(
    'skin' => array(
      'title' => 'Skin Gallery',
      'page callback' => 'os_poker_skin_index',
      'access arguments' => array('access content'),
    ),
    'skin/gadget' => array(
      'title' => 'Gadget',
      'page callback' => 'os_poker_skin_gadget',
      'access arguments' => array('access content'),
    ),
  );
}

function os_poker_skin_index() {
  return 'Skin Gallery';
}

function os_poker_skin_gadget() {
  global $user;
  $result    = db_query("SELECT * FROM {applications} WHERE title = 'jpoker-skin2'");
  $app = db_fetch_object($result);
	if (!$app) {
    return "Please install jpoker-opensocial-skin.xml";
	}
  return theme('add_gadget', $app->id, 0, "canvas", $user->uid);
}
