<?php

function fb_integration_user($op, &$edit, &$account, $category = NULL) {


    $user = $account;

    if ($op!='login') {
        return;
    }


    if (!isset($user->fbu)) {
        return;
    }


    global $fb;
    //fb_get_friends($user->fbu);
    //$items = $fb->api_client->friends_getAppUsers();
    //print_r($items);
    //$friends_ids = fb_user_get_local_friends($user->fbu);
    //print_r($friends_ids);

    $fbus = $fb->api_client->friends_getAppUsers();//array(1328933654,100000684168920,100001206182306 ) ;

    $query = "SELECT uid FROM {authmap}
        left join {user_relationships} on {user_relationships}.requestee_id = {authmap}.uid
	and {user_relationships}.requester_id=%s
        WHERE authname IN (%s) AND module='%s'  and {user_relationships}.requestee_id is null"  ; // better? way using authmap.
    $args[] = $user->uid;
    $args[] = implode(',', $fbus);
    $args[] = 'fb_user';

    $result = db_query($query, $args);
    $uids = array();
    while ($data = db_fetch_object($result)) {
      if ($data->uid) {
        $uids[] = $data->uid;
      }
    }
    if (count($uids)==0) {
        return ;
    }
    $rtype = user_relationships_type_load(array('name'=>'buddy'));

    for ($i=0;$i<count($uids);$i++) {
      $relationship = new stdClass();
      $relationship->requestee_id = $uids[$i];
      $relationship->requester_id=$user->uid;
      $relationship->rtid =$rtype->rtid;
      $relationship->approved = 1;
      user_relationships_save_relationship($relationship,'fbapprove');
    }


}
function fb_integration_form_os_poker_first_profile_form_alter(&$form,&$form_state) {
    global $user;
    global $fb;

    if (isset($user->fbu) ) {
        //print_r($form['profile_nickname']);
        //$info = fb_users_getInfo(array($user->fbu));



        try {
        $info = $fb->api_client->users_getStandardinfo(array($user->fbu),array('name','first_name','sex','current_location','locale','birthday'));
        $info=$info[0];
        if ($info['locale']!='') {
            $locales = explode('_',$info['locale']);
            $locale = strtoupper($locales[0]);
            $form['profile_country']['#default_value'] = $locale;
        }

        $form['profile_city']['#default_value'] = $info['current_location'];
        $form['profile_nickname']['#default_value']=$info['name'];


		
        $sex = strtolower($info['sex']);
        if ($info['sex']=='male') {
            $form['profile_gender']['#default_value']='Male';
            //$sex=='male'?$form['profile_gender']['#default_value']='Male':$form['profile_gender']['#default_value']='Female';
        }else if ($info['sex']=='female') {
            $form['profile_gender']['#default_value']='Female';
        }
        	db_query ("update {users} set picture='https://graph.facebook.com/".$user->fbu."/picture?type=large' where uid=%s",array($user->uid));
        }catch (Exception $e) {

        }

    }
}

?>