<?php
//
//    Copyright (C) 2009, 2010 Pokermania
//    Copyright (C) 2010 OutFlop
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
/* This file has been autogenerated by update-poker-class.php */
function os_poker_get_all_rewards() {
	return array(
	'reward1'	=> array('value' => 0, 'name' => t("Newcomer"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player sits down at the table for the first time")),
	'reward2'	=> array('value' => 0, 'name' => t("Blind Hen"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins his first hand")),
	'reward3'	=> array('value' => 0, 'name' => t("It's taking part that counts!"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player participates in a tourney/sng for the first time")),
	'reward4'	=> array('value' => 0, 'name' => t("Bullets"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with AA hole cards")),
	'reward5'	=> array('value' => 0, 'name' => t("Cowboys"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with KK hole cards")),
	'reward6'	=> array('value' => 0, 'name' => t("Jailhouse Rock"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with QQ hole cards")),
	'reward7'	=> array('value' => 0, 'name' => t("Fish-Hooks"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with JJ hole cards")),
	'reward8'	=> array('value' => 0, 'name' => t("Route 66"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with 66 hole cards")),
	'reward9'	=> array('value' => 0, 'name' => t("Sailboats"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with 44 hole cards")),
	'reward10'	=> array('value' => 0, 'name' => t("Big Slick"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with AK hole cards")),
	'reward11'	=> array('value' => 0, 'name' => t("Big Chick"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with AD hole cards")),
	'reward12'	=> array('value' => 0, 'name' => t("Dinner for two"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with 69 hole cards")),
	'reward13'	=> array('value' => 0, 'name' => t("Valentines's Day"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins with KQ hole cards, both heart")),
	'reward14'	=> array('value' => 0, 'name' => t("Big Bang 5.000"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins a big pot, more than 5.000 chips")),
	'reward15'	=> array('value' => 0, 'name' => t("No risk no fun"), 'color' => "Bronce", 'points' => 100, 'bonus' => 1000, 'picture' => "", 'desc' => t("Player wins an all-in")),
	'reward16'	=> array('value' => 0, 'name' => t("Be my Buddy I"), 'color' => "Bronce", 'points' => 200, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player has at least 5 buddies")),
	'reward17'	=> array('value' => 0, 'name' => t("Follow me I"), 'color' => "Bronce", 'points' => 200, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player has at least 2 successful invitations")),
	'reward18'	=> array('value' => 0, 'name' => t("Regular's Table"), 'color' => "Bronce", 'points' => 200, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player sits down at the table with at least one buddy")),
	'reward19'	=> array('value' => 0, 'name' => t("It's my round!"), 'color' => "Bronce", 'points' => 200, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player buys a gift for every player at the table, value doesn't matter")),
	'reward20'	=> array('value' => 0, 'name' => t("Challenger"), 'color' => "Bronce", 'points' => 200, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player participates in a challenge")),
	'reward21'	=> array('value' => 0, 'name' => t("Jackpot"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins with 777")),
	'reward22'	=> array('value' => 0, 'name' => t("Trips"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins with three of a kind")),
	'reward23'	=> array('value' => 0, 'name' => t("Ten Times Trips"), 'color' => "Silver", 'points' => 250, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with three of a kind, 10 times")),
	'reward24'	=> array('value' => 0, 'name' => t("Road Testing"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins with a street")),
	'reward25'	=> array('value' => 0, 'name' => t("On The Road"), 'color' => "Silver", 'points' => 250, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with a street, 10 times")),
	'reward26'	=> array('value' => 0, 'name' => t("Flush"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins with a flush")),
	'reward27'	=> array('value' => 0, 'name' => t("Flush 10x"), 'color' => "Silver", 'points' => 250, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with a flush, 10 times")),
	'reward28'	=> array('value' => 0, 'name' => t("Full House"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins with a full house")),
	'reward29'	=> array('value' => 0, 'name' => t("Full House 10x"), 'color' => "Silver", 'points' => 250, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with a full house, 10 times")),
	'reward30'	=> array('value' => 0, 'name' => t("Broadway"), 'color' => "Silver", 'points' => 250, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player wins with AKQJT")),
	'reward31'	=> array('value' => 0, 'name' => t("The Bicycle"), 'color' => "Silver", 'points' => 250, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player wins with A2345")),
	'reward32'	=> array('value' => 0, 'name' => t("Big Bang 10.000"), 'color' => "Silver", 'points' => 250, 'bonus' => 2000, 'picture' => "", 'desc' => t("Player wins a big pot, more than 10.000 chips")),
	'reward33'	=> array('value' => 0, 'name' => t("Big Bang 25.000"), 'color' => "Silver", 'points' => 250, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player wins a big pot, more than 25.000 chips")),
	'reward34'	=> array('value' => 0, 'name' => t("Bad Beat Full House"), 'color' => "Silver", 'points' => 250, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player holds a full house and looses his hand")),
	'reward35'	=> array('value' => 0, 'name' => t("Final Table"), 'color' => "Silver", 'points' => 250, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player places top 9 in a tourney")),
	'reward36'	=> array('value' => 0, 'name' => t("Lounge Lizard"), 'color' => "Silver", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player has at least 10 buddies")),
	'reward37'	=> array('value' => 0, 'name' => t("Randy Dandy"), 'color' => "Silver", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player has at least 5 successful invitations")),
	'reward38'	=> array('value' => 0, 'name' => t("Regular's Table II"), 'color' => "Silver", 'points' => 500, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player sits down at the table with at least three buddies")),
	'reward39'	=> array('value' => 0, 'name' => t("It's my round! II"), 'color' => "Silver", 'points' => 500, 'bonus' => 2500, 'picture' => "", 'desc' => t("Player buys a gift for every player at the table, aggregate value more than 1.000 Chips")),
	'reward40'	=> array('value' => 0, 'name' => t("The Millionaires Club"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player has a peek chip count of 1.000.000 chips")),
	'reward41'	=> array('value' => 0, 'name' => t("On a Rush"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins 10 hands in a row during a session")),
	'reward42'	=> array('value' => 0, 'name' => t("Quads"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with four of a kind")),
	'reward43'	=> array('value' => 0, 'name' => t("Straight Flush"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with a straight flush")),
	'reward44'	=> array('value' => 0, 'name' => t("The Road to Success"), 'color' => "Gold", 'points' => 500, 'bonus' => 7500, 'picture' => "", 'desc' => t("Player wins with a street, 50 times")),
	'reward45'	=> array('value' => 0, 'name' => t("Flush Rush"), 'color' => "Gold", 'points' => 500, 'bonus' => 7500, 'picture' => "", 'desc' => t("Player wins with a flush, 50 times")),
	'reward46'	=> array('value' => 0, 'name' => t("House-Hunter"), 'color' => "gold", 'points' => 500, 'bonus' => 7500, 'picture' => "", 'desc' => t("Player wins with a full house, 50 times")),
	'reward47'	=> array('value' => 0, 'name' => t("Big Bang 100.000"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins a big pot, more than 100.000 chips")),
	'reward48'	=> array('value' => 0, 'name' => t("Kamikaze"), 'color' => "Gold", 'points' => 500, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player wins with 27 hole cards, any suit")),
	'reward49'	=> array('value' => 0, 'name' => t("Bad Beat Quads"), 'color' => "Gold", 'points' => 500, 'bonus' => 10000, 'picture' => "", 'desc' => t("Player holds four of a kind and looses his hand")),
	'reward50'	=> array('value' => 0, 'name' => t("Tournament Pro"), 'color' => "Gold", 'points' => 500, 'bonus' => 7500, 'picture' => "", 'desc' => t("Player wins a tourney")),
	'reward51'	=> array('value' => 0, 'name' => t("Cool Dude"), 'color' => "Gold", 'points' => 1000, 'bonus' => 7500, 'picture' => "", 'desc' => t("Player has at least 50 buddies")),
	'reward52'	=> array('value' => 0, 'name' => t("Party Animal"), 'color' => "Gold", 'points' => 1000, 'bonus' => 10000, 'picture' => "", 'desc' => t("Player has at least 25 successful invitations")),
	'reward53'	=> array('value' => 0, 'name' => t("Private Table"), 'color' => "Gold", 'points' => 1000, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player sits down at the table with 8 buddies")),
	'reward54'	=> array('value' => 0, 'name' => t("It's my round! III"), 'color' => "Gold", 'points' => 1000, 'bonus' => 5000, 'picture' => "", 'desc' => t("Player buys a gift for every player at the table, aggregate value more than 10.000 Chips")),
	'reward55'	=> array('value' => 0, 'name' => t("Royal Family"), 'color' => "Platinum", 'points' => 2000, 'bonus' => 10000, 'picture' => "", 'desc' => t("Player wins with a royal flush")),
	'reward56'	=> array('value' => 0, 'name' => t("Marathon"), 'color' => "Platinum", 'points' => 2000, 'bonus' => 15000, 'picture' => "", 'desc' => t("at least 42 hours at the table within 8 days")),
	'reward57'	=> array('value' => 0, 'name' => t("Strike!"), 'color' => "Platinum", 'points' => 2000, 'bonus' => 20000, 'picture' => "", 'desc' => t("all achievements complete")),
	'reward58'	=> array('value' => 0, 'name' => t("Milestone"), 'color' => "Platinum", 'points' => 2000, 'bonus' => 20000, 'picture' => "", 'desc' => t("10.000 hands played")),
	'reward59'	=> array('value' => 0, 'name' => t("Tournament Expert"), 'color' => "Platinum", 'points' => 2000, 'bonus' => 20000, 'picture' => "", 'desc' => t("Player wins at least 10 tourneys")),
	'reward60'	=> array('value' => 0, 'name' => t("Donald Trump"), 'color' => "Platinum", 'points' => 5000, 'bonus' => 25000, 'picture' => "", 'desc' => t("Player had more than 1 million chips, lost everything and has again > 1 million chips")),
	'reward61'	=> array('value' => 0, 'name' => t("Big Spender"), 'color' => "Platinum", 'points' => 5000, 'bonus' => 10000, 'picture' => "", 'desc' => t("Player buys a gift for every player at the table, aggregate value more than 100.000 Chips")),
	'reward62'	=> array('value' => 0, 'name' => t("Buddy King"), 'color' => "Platinum", 'points' => 5000, 'bonus' => 15000, 'picture' => "", 'desc' => t("Player has at least 100 buddies")),
	'reward63'	=> array('value' => 0, 'name' => t("Invitation King"), 'color' => "Platinum", 'points' => 5000, 'bonus' => 25000, 'picture' => "", 'desc' => t("Player has at least 50 successful invitations")),
	'reward64'	=> array('value' => 0, 'name' => t("Playboy"), 'color' => "Platinum", 'points' => 5000, 'bonus' => 25000, 'picture' => "", 'desc' => t("Player has spent at least 1.000.000 chips for gifts")),
);
}
?>
