<?php 
require_once('os_integration.api.inc');
require_once('os_integration_invite_block.inc');

function os_integration_create_profile_callback($myspace_profile_id) {
	os_integration_create_profile($myspace_profile_id);
	drupal_goto('poker/first_profile');
}

function os_integration_admin_settings(){
	$form['os_integration_consumer_key']=array(
		'#type'=>'textfield',
		'#default_value'=>variable_get('os_integration_consumer_key',array()),
		'#title'=>'OAuth Consumer Key');
	$form['os_integration_consumer_secret']=array(
		'#type'=>'textfield',
		'#default_value'=>variable_get('os_integration_consumer_secret',array()),
		'#title'=>'OAuth Consumer Secret');
	return system_settings_form($form);
}
function os_integration_menu() {
	$items = array();

	// Admin pages overview.
	$items['os_integration_create_user/%'] = array(
    'title' => 'Opensocial create profile',
    'description' => 'creates profile and forward to /first_profile',
    'page callback' => 'os_integration_create_profile_callback',
    'access arguments' => array('access content'),
    'page arguments' => array(
	1
	),
    'type' => MENU_CALLBACK,
	);
	$items['admin/build/os_integration_admin'] = array(
    'title'=>'Opensocial',
    'description'=>'Opensocial integration configuration ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_integration_admin_settings'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function os_integration_form_os_poker_first_profile_form_alter(&$form,&$form_state) {
	global $user;
	if (isset($user->_osu) ) {
		$profile = os_integration_get_profile_infos($user->_osu);
		$folder =  file_directory_path().'/os_pictures';
		$url = $profile->thumbnailUrl;
		file_check_directory($folder,FILE_CREATE_DIRECTORY);
		$file= $folder.'/pic_'.$user->_osu.'.jpg';
		file_save_data(file_get_contents($url),$file);
		db_query ("update {users} set picture='".$file."' where uid=%s",array($user->uid));
		try {
			$form['profile_nickname']['#default_value']=$profile->displayName;
			if (isset($profile->currentLocation['country'])) {
				$form['profile_country']['#default_value'] = $profile->currentLocation['country'];
			}
			if ($profile->birthday!='') {
				$birthday = explode('T',$profile->birthday);
				$birthday = $birthday[0];
				$birthdayAry = explode('-',$profile->birthday);
				if (count($birthdayAry)==3) {
					$form['profile_dob']['#default_value']['day']=(int)$birthdayAry[2];
					$form['profile_dob']['#default_value']['month']=(int)$birthdayAry[1];
					$form['profile_dob']['#default_value']['year']=$birthdayAry[0];
				}
			}
			$form['profile_city']['#default_value']=$profile->currentLocation['locality'];
			$sex = strtolower($profile->gender);
			if ($sex=='male' ) {
				$form['profile_gender']['#default_value']='Male';
			}else if ($sex=='female') {
				$form['profile_gender']['#default_value']='Female';
			}
		}catch (Exception $e) {
			watchdog('opensocial error', $e->getMessage());
		}
	}
}
function os_integration_addjs($myspace_profile_id)  {
	drupal_add_js(drupal_get_path('module','os_integration').'/js/IFPC_externalIframe011.js');
	drupal_add_js('
gadgets.rpc.setRelayUrl(\'..\', \'http://profile.myspace.com/Modules/Applications/Pages/rpc_relay.aspx\'); 
// set the correct panel id. The name will be apppanel_XXXXXX_canvas where
// XXXXXX is the id of the application
    MyOpenSpace.MySpaceContainer.get().registerParam("panelId", "apppanel_'.$_REQUEST['appid'].'_canvas");
//Set the location of the ifpc_relay_external001.html within your server
    MyOpenSpace.MySpaceContainer.get().registerParam("localRelay", "http://'.$_SERVER['HTTP_HOST'].'/'.drupal_get_path('module','os_integration').'/relay.html");

    function os_integration_call_regist_user() {
    	window.location.href=\'/os_integration_create_user/'.$myspace_profile_id.'\'; 
    }
    function os_integration_requestPermission(){
    	
		var permissionValue = "VIEWER_FULL_PROFILE_INFO";
		var container = MyOpenSpace.MySpaceContainer.get();
		var permission = MyOpenSpace.Permission[permissionValue];
		
		var hasPermission = container.hasPermission(permission);
		
		if (hasPermission){
			os_integration_call_regist_user();
			
			return;
		}
		var callback = function (response){
			var responseText;
			
			if (response.errorMessage){
				responseText = "Error: " + response.errorMessage;
				if (response.permissions){
					responseText += "Permissions granted:<br />"
					for (var i in permission){
						responseText += "<br />" + permission.permission;
					}
				}
				alert(responseText);
			}
			else if (response.permissions){
					os_integration_call_regist_user();
			}
		}
		
		container.requestPermission(permission,"Test permission request", callback);
	}

	
    //;
','inline');
}

function os_integration_user($op, &$edit, &$account, $category = NULL) {
    
    if ($op!='login') {
        return;
    }
    if (isset($account->_osu)) {
		os_integration_map_friends($user->_osu,$account);
    }
}
function os_integration_init()  {
	global $user;
	
	if (!isset($_REQUEST['opensocial_viewer_id'])) {
		return ;
	}
	
	$myspace_profile_id = $_REQUEST['opensocial_viewer_id'];
	os_integration_addjs($myspace_profile_id) ;
	if ($user->uid!=0 && isset($user->_osu) && $user->_osu==$myspace_profile_id) {
		return ;
	}
	
	if (($user->uid!=0 && !isset($user->_osu)) || (isset($user->_osu) && $user->_osu!=$myspace_profile_id)) {
		session_destroy();
		$user = drupal_anonymous_user();
	}
	
	if (os_integration_login_opensocial_user($myspace_profile_id)==true) {
		return ;
	}
	drupal_add_js('os_integration_requestPermission();','inline');
}
?>