# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient
from signup import signup

def test_fold():
    client = WindmillTestClient(__name__)
    signup(client)
    client.click(id=u'play-now-button')
    client.waits.forElement(classname=u'jpoker_table')
    for i in range(100):
        client.click(classname=u'jpoker_ptable_fold')
        client.waits.sleep(milliseconds=5000)
